//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POE.Assessment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleInformation
    {
        public int Id { get; set; }
        public int StudentInformationId { get; set; }
        public int CodeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int NumberOfCredits { get; set; }
        public int ClassHoursPerWeek { get; set; }
        public int HoursOfSelfStudy { get; set; }
        public Nullable<decimal> SelfStudyHoursPerWeek { get; set; }
        public System.DateTime StudyDate { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual StudentInformation StudentInformation { get; set; }
    }
}
